Feature/recycle
arcadia-redux/reVolt pull request #102
Opened 2021-05-27 22:03 UTC by Nibuja05

Adds the recycling mechanic to the Anvil:

- Changed worth calculations of weapons to now be based on XP and represent shards instead of gold
- Added new random element, for various scenarios
- Added recycling option to anvil
- Added confirm mechanic anvil (used for recycling)
- Added options to show preview shards in the anvil output

Other Additions:
- Added round pause and the option to toggle it, by clicking on the timer

Other Fixes:
- Fixes #86 
- Fixed broken shard counter after absorbing

2021-05-28 08:55 UTC, Shushishtok approved these changes

2021-05-28 08:55 UTC, Shushishtok commented on content/panorama/scripts/custom_game/shop.ts
> +		// do something
Do something, make it smooth :D
(seriously though, do something about that xD)

2021-05-28 08:55 UTC, Shushishtok commented on game/scripts/vscripts/core/shop_manager.ts
> +		for (let i = 0; i <= shardCount; i++) {
Can this be changed in a way that gets remaining shards, rolls a number of shards (up to the max) and an element, then adds that? Less loops and events.

For instance, if I have 10 shards:
* Roll a number between 1 and 10 - say I get 3
* Roll an element - say I get Frost
* The player gets 3 Frost Shards, now there are 7 shards remaining
* Roll a number between 1 and 7 - say I get 5
* Roll an element - say I got Fire
* The player gets 5 Fire Shards, now there are 2 shards remaining
* Roll a number between 1 and 2 - say I get 2
* Roll an element - say I got Wind
* The player gets 2 Wind Shards, now there are 0 shards remaining and we can move on.

The process can be refined even further, e.g. max random shards per cycle can only be up to 5 in case you have more than 5, to make sure it doesn't just give all shards for a single element if you're lucky.

2021-05-28 08:55 UTC, Shushishtok commented on game/scripts/vscripts/core/weapon_base.ts
> +		let xpWorth = Math.floor(this.xp / 30);
Should be changed to something easily adjustable, e.g. `Math.floor(this.xp * 20 * 0.01 / 10)`.
The "20" above should be its own variable.

2021-05-30 14:39 UTC, Nibuja05 commented on content/panorama/scripts/custom_game/shop.ts
> +		// do something
ok, I realized that always smoothes out here, so no need to specify that ^^

2021-05-30 15:03 UTC, Nibuja05 commented on game/scripts/vscripts/core/shop_manager.ts
> +		for (let i = 0; i <= shardCount; i++) {
used here a `DefaultMap` instead, works 👍

2021-05-30 15:21 UTC, Nibuja05 commented
- Added `Constants.ts` to keep track of all constant value we need to keep track of.
I changed all I found, but I might have missed some. We can continue to move them to there with time.

- Also added `DefaultMap` (inspired by pythons `DefautlDict`). Its the same as a normal map, improves the get function. More info at its documentation in `Util`.
Feel free to use it anywhere you want.

2021-05-30 15:32 UTC, Shushishtok approved these changes

2021-05-30 15:40 UTC, Shushishtok requested changes
Attempting to fix issue with pushing

2021-05-30 15:41 UTC, Shushishtok approved these changes

2021-05-30 15:44 UTC, merged