Feature/weapon effect tooltips
arcadia-redux/reVolt pull request #145
Opened 2021-06-06 15:37 UTC by Nibuja05

Fixed #141 

Automatically marks all generic weapon effects in the description of any rune and displays an info box for it:
- to use this feature, simply use the `GenericWeaponEffectName` enum in the localization of any rune or generic effect description
- alternatively you can directly use: `%burning%`, `%zapping%` etc

- info box is only displayed while alt is pressed

2021-06-06 18:06 UTC, Shushishtok requested changes
Really good work! Some suggestions to make it super perfect :D

2021-06-07 11:24 UTC, Nibuja05 commented on common/weapons.d.ts
> +declare const enum GenericWeaponEffectName {
Done.

2021-06-07 11:30 UTC, Nibuja05 commented on content/panorama/scripts/custom_game/util.ts
> +function LocalizeGenericWeaponEffectName(effect: GenericWeaponEffectName): string {
Done.

2021-06-07 11:30 UTC, Nibuja05 commented on content/panorama/scripts/custom_game/util.ts
> +	} else if (!GameUI.IsAltDown() && altDown == true) {
Done.

2021-06-07 11:30 UTC, Nibuja05 commented on content/panorama/scripts/custom_game/weapon_base.ts
> +		if (newText.indexOf(effect) >= 0) {
Done.

2021-06-07 11:31 UTC, Nibuja05 commented on content/panorama/scripts/custom_game/weapon_base.ts
> +		if (text.indexOf(`%${value.name}%`) >= 0) {
Done.

2021-06-07 11:32 UTC, Nibuja05 commented on content/panorama/styles/custom_game/weapon_base.css
> +	/* margin-bottom: 6px; */
Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done. Done.

2021-06-07 11:32 UTC, Nibuja05 commented on content/panorama/styles/custom_game/weapon_base.css
> +	/* background-color: rgb(65, 65, 65); */
Done.

2021-06-07 11:34 UTC, Nibuja05 commented on content/panorama/scripts/custom_game/util.ts
> +	if (GameUI.IsAltDown() && altDown == false) {
Done.

2021-06-07 15:27 UTC, Shushishtok approved these changes

2021-06-07 15:30 UTC, merged