Wave default values and smart logic
arcadia-redux/reVolt pull request #32
Opened 2021-04-25 10:11 UTC by Shushishtok

- Localized existing wave names.
- Added default values for: unit health, unit damage, unit move speed, wave interval and wave max unit count. Those can now be omitted when defining a wave, or overridden if we want a specific value to be used.
- Added four AI logic types. They're designated to stay dumb, but control the way the AI controls its units. The options are:
    - Touch only: the unit simply try to touch the player, dying and dealing damage when it does.
    - Cast only: the unit only casts whatever abilities it has, otherwise it is idle. Useful for units that has some kind of projectile that they will try to fire at the player with very low cooldown.
    - Cast and touch: the unit tries to casts whatever abilities it has. If it cannot, it will try to touch the player instead. Useful for units that have abilities but should still try to touch the player.
    - Run away: currently unique to round 1. Not fully implemented yet. Units with this AI logic will constantly try to run away from the player.
    
**Note:** ability casting AI is currently "dumb" - it assumes a single target unit targeting ability on the player. Later on, as we design and implement more abilities, we can rework the AI to take multiple ability behavior types and handle them accordingly.

- Added direction calculation util functions.
- Added util functions for determining whether a unit is capable of casting an ability on a target, if any. (target is optional, e.g. on cases of No Target abilities).
- Localization files can now reference types/enums found on the d.ts. files in the /common directory.
- Renamed Sides to Side.

2021-04-25 12:04 UTC, Nibuja05 requested changes
Good job! Looks good so far
Can you also take a look at my changes? 😅

2021-04-25 12:04 UTC, Nibuja05 commented on game/scripts/vscripts/core/wave_manager.ts
> +				}
missing break here

2021-04-26 17:30 UTC, Shushishtok commented on game/scripts/vscripts/core/wave_manager.ts
> +				}
Fixed in latest commit

2021-04-26 17:35 UTC, Nibuja05 approved these changes
Nice, everythings ok now 👍

2021-04-26 17:35 UTC, merged