Add enemy drops/loot
arcadia-redux/reVolt pull request #63
Opened 2021-04-30 19:25 UTC by Nibuja05

Fixes #42, #35
Added weapon fragments, that can be used later for weapon upgrades, crafting etc.

- Added `ShopManager` for managing fragment related functions
- Added `loot_count` to wave infos and enemy fragment drops on kill
- Added gold gain on unit kills
- Added particle effects for fragment drops
- Added custom UI at bottom right fragment storage
- Added gold display on custom UI
- Added space for player information on custom UI (+ added life counter)

- Fixed wave names not clearing properly when rounds end with dev command

2021-04-30 20:32 UTC, Shushishtok requested changes

2021-04-30 20:32 UTC, Shushishtok commented on content/panorama/scripts/custom_game/resources.ts
> +		if (!count) {
Up to you: you could do it in one line e.g.:

`count ? fragment.Add() : fragment.SetCount(count);`

Fine as is, so you can ignore it if you want.

2021-04-30 20:32 UTC, Shushishtok commented on content/panorama/scripts/custom_game/resources.ts
> +	if (count && count === 0) return;
Is there any reason you'll specifically pass count with value 0? Most likely, the count variable will be ignored.

2021-04-30 20:32 UTC, Shushishtok commented on content/panorama/scripts/custom_game/resources.ts
> +	private type: WeaponElement;
Just for the sake of clarity, can we replace `type` with `element`?

2021-04-30 20:32 UTC, Shushishtok commented on content/panorama/scripts/custom_game/resources.ts
> +		PanoramaWeaponFragment.fragments[fragment.name][fragment.tier] = fragment;
I wonder if it won't be easier to use a map here, just because of the two-fold naming scheme. Up to you!

2021-04-30 20:32 UTC, Shushishtok commented on content/panorama/scripts/custom_game/resources.ts
> +		this.label.text = "" + this.count;
You can replace `"" + this.count` with `this.count.toString()`, to improve clarity.

2021-04-30 20:32 UTC, Shushishtok commented on content/panorama/scripts/custom_game/resources.ts
> +	ClearFragmentsRaw();
Is this supposed to be `ClearFragmentsRow()`?

2021-04-30 20:32 UTC, Shushishtok commented on content/panorama/scripts/custom_game/resources.ts
> +	label.text = "" + amount;
amount.toString() for better clarity

2021-04-30 20:32 UTC, Shushishtok commented on content/panorama/styles/custom_game/resources.css
> +	/* background-color: gradient(linear, 0% 0%, 0% 100%, from(rgb(34, 34, 34)), to(rgb(22, 22, 22))); */
Remove if not needed

2021-04-30 20:32 UTC, Shushishtok commented on content/panorama/styles/custom_game/resources.css
> +	/* letter-spacing: 0.5px; */
Remove if no longer needed

2021-04-30 20:32 UTC, Shushishtok commented on content/panorama/styles/custom_game/resources.css
> +	/* background-color: gray; */
Remove if no longer needed

2021-05-03 09:25 UTC, Nibuja05 commented on content/panorama/scripts/custom_game/resources.ts
> +	ClearFragmentsRaw();
no, its using raw xml instead of js.
The name is intended

2021-05-03 09:25 UTC, Nibuja05 commented on content/panorama/scripts/custom_game/resources.ts
> +	ClearFragmentsRaw();
renamed it to `ClearFragmentsXml` for better clarity

2021-05-03 09:26 UTC, Nibuja05 commented on game/scripts/vscripts/GameMode.ts
> +		Timers.CreateTimer(2, () => {
nope

2021-05-03 09:55 UTC, Shushishtok approved these changes

2021-05-03 09:56 UTC, merged