Feature/mouse movement improvement
arcadia-redux/reVolt pull request #72
Opened 2021-05-05 18:12 UTC by Nibuja05

Fixes #70, #57, #16, #36

- Adds  `ShopManager` for gold and shard management
- Adds new hotkey for center inventory and dev tools
- Changed hotkeys to `1`, `2` and `3`
- Added `Settings` namespace for managing player settings on server
- Added temporary mouse movement disable (when UI opens somewhere)
- Prepared for permanent mouse movement disable (mentions #44)
- Added automatic shop close on mouse click outside the shop

2021-05-05 19:42 UTC, Shushishtok requested changes

2021-05-05 19:42 UTC, Shushishtok commented on content/panorama/scripts/custom_game/settings.ts
> +AddNewKeybind("3", "open_dev", DevToggle);
I would probably only do the bind if this is:
- A tools mode game
- A cheat mode game.

Otherwise this portion shouldn't be used and/or visible in the settings at all.

2021-05-05 19:42 UTC, Shushishtok commented on content/panorama/scripts/custom_game/shop.ts
> +	// Disabled, until a working solution was found:
If it's not working, just remove this part. On my talent manager it works as long as you have focus on the panel, which is probably why it's not working for you.

Instead of just having it commented out, decide: either you try to make it work, or you remove this part completely.

2021-05-05 19:42 UTC, Shushishtok commented on game/scripts/vscripts/GameMode.ts
> +			let units = event.units;
Please move the content of the filter to a separate function, similar to the SetModifyExperienceFilter. This function is only for registering the filters; if it would also be the content of every filter, it would get messy very quickly.

2021-05-05 19:42 UTC, Shushishtok commented on game/scripts/vscripts/GameMode.ts
> +				if (unit.GetUnitName() === GenericUnitName.PlayerHero && unit.IsRealHero()) {
Since we're going to introduce multiple units, we could probably stop doing the GetUnitName() check and instead simply use IsRealHero(). Let's assume that only players are heroes - enemies and bosses are not.

2021-05-05 19:42 UTC, Shushishtok commented on game/scripts/vscripts/core/settings.ts
> +			mouseMoveTempDisabled: 0,
Why not false, like with mouseMove? I know you need to translate it with what you get/send as events, but that's way easier when needing to handle it on the server logic. For consistency, please make both variables booleans.

2021-05-05 19:42 UTC, Shushishtok commented on game/scripts/vscripts/core/settings.ts
> +		if (settings.mouseMoveTempDisabled > 0) return false;
I don't like this line - convert to boolean as explained above.

2021-05-05 19:42 UTC, Shushishtok commented on game/scripts/vscripts/core/settings.ts
> +		if (disable === true) {
Pretty sure you don't need to do `=== true`, just `disable` will be evaluated to true.

2021-05-05 19:42 UTC, Shushishtok commented on content/panorama/scripts/custom_game/settings.ts
>  /**
Should the custom keybinds menu also temporarily stop mouse movement tracking?

2021-05-05 19:42 UTC, Shushishtok commented on game/scripts/vscripts/core/hero_spin.ts
> +				if (cursorDistance > 10) {
While this change improves the movement by mouse control, there is still an issue where you become very sticky to walls even when you move the mouse.

See example video of what I mean:
https://streamable.com/i3jtx0

Note at the stickyness of IO compared to my mouse position.
This also occurs on regular rightclicks, so it probably has to do with Dota's pathing on unreachable locations.

This probably can be overridden by changing clicks to register within the closest valid position inside the arena (or any other math that you can think of ;p). Use the order filter to override.

2021-05-06 14:26 UTC, Nibuja05 commented on game/scripts/vscripts/core/hero_spin.ts
> +				if (cursorDistance > 10) {
I accidentally commented the clipping logic out...
Its working fine now 👍

2021-05-06 14:28 UTC, Nibuja05 commented on content/panorama/scripts/custom_game/settings.ts
>  /**
Not important until the settings menu is working (currently there is only keybind changes, which are broken)

2021-05-07 09:56 UTC, Shushishtok approved these changes

2021-05-07 09:56 UTC, Shushishtok commented
Just need to resolve conflicts and we can merge it. Great work!

2021-05-07 13:02 UTC, merged