Feature/absorb
arcadia-redux/reVolt pull request #87
Opened 2021-05-15 16:47 UTC by Nibuja05

Fixes #81 
Implements the absorbing feature, containing:

- weapon rework from levels to XP. Levels still exists, but are no longer edited, they are automatically calculated by their xp value.
- weapon tooltips now show their current xp progress until the next level.
- weapon tooltips now show when they are max level.
- added various missing tooltip localizations.
- renamed the anvil "Combine" to "Absorb".
- added shard flyout to the shop, which shows current shard values and lets the user select them for upgrading (shift-click moves all)
- added weapon preview before absorbing
- add absorb server-side (adds xp by selected shards)

Fixes #55 
- several adjustments on weapon tooltips in general, fixed level problems and tooltip artifacts (bug when quickly hovering over different weapons, fixed)

2021-05-15 17:32 UTC, Shushishtok commented
Seems like #55 is still occurring on the inventory. Still need to fix that.

![image](https://user-images.githubusercontent.com/15510811/118372929-b16b2400-b5bc-11eb-9a73-d5e1697c57a7.png)
This only happens in the inventory, in the shop it's looking good.

2021-05-15 18:32 UTC, Shushishtok requested changes

2021-05-15 18:32 UTC, Shushishtok commented on content/panorama/scripts/custom_game/shop.ts
> +	if ((nextLabel as LabelPanel).text === "Upgrade") {
I think you can now use use GetCurrentAnvilFunction instead of that.

2021-05-15 18:32 UTC, Shushishtok commented on content/panorama/scripts/custom_game/shop.ts
> +	if ((nextLabel as LabelPanel).text === "Absorb") {
I think you can now use use GetCurrentAnvilFunction instead of that.

2021-05-15 18:32 UTC, Shushishtok commented on content/panorama/scripts/custom_game/shop.ts
> +function SelectUpgradeAmount() {}
You can completely remove that, unless you're planning to keep it for reference purposes.

2021-05-15 18:32 UTC, Shushishtok commented on content/panorama/scripts/custom_game/shop.ts
> +	if (type === AnvilType.Enchant) {
This if/else ifs could be transformed into a switch.

2021-05-15 18:32 UTC, Shushishtok commented on content/panorama/scripts/custom_game/shop.ts
> +		// OnAbsorbFinish(event);
Is the comment out intended? Event doesn't do anything when called right now.

2021-05-15 18:32 UTC, Shushishtok commented on content/panorama/scripts/custom_game/weapon_base.ts
> +			// let text = `${transformedName}:   ${MarkText(curVal)}${UnmarkText(" / " + nextVal)}`;
If comment is not needed, please remove it.

2021-05-15 18:32 UTC, Shushishtok commented on content/panorama/scripts/custom_game/weapon_base.ts
> +		let isMaxLevel = this.level >= this.maxLevel;
I think there's a proper function with the same name that you can access when accessing a shard. Consider using that instead.

2021-05-15 18:32 UTC, Shushishtok commented on game/scripts/vscripts/core/weapon_base.ts
> +		if (this.wGetElement() === element) return true;
This needs to be expanded later on to support multiple elements.

2021-05-15 18:32 UTC, Shushishtok commented on game/scripts/vscripts/core/weapon_manager.ts
> +				maxLevel: 10,
The max level should probably also be part of the weaponData, so we can decide on maxLevels for specific weapons. Defaults to 10 if omitted.

2021-05-16 10:15 UTC, Nibuja05 commented on content/panorama/scripts/custom_game/shop.ts
> +		let [usedCount, _] = weaponShardCounters.get(name)!;
thats sadly not possible with array deconstruction syntax :/
since weaponShard and weaponShardCounters are set in the same place, there is no way that the first one could be defined, and not the second

2021-05-16 10:19 UTC, Shushishtok commented on content/panorama/scripts/custom_game/shop.ts
> +		let [usedCount, _] = weaponShardCounters.get(name)!;
Fair enough!

2021-05-16 10:19 UTC, Nibuja05 commented on content/panorama/scripts/custom_game/shop.ts
> +	if ((nextLabel as LabelPanel).text === "Upgrade") {
sadly it cannot, since `GetCurrentAnvilFunction` retrieves the current anvil function and this checks for the **next** anvil function. Its only used here, so I haven't bothered about making it into a function

2021-05-16 10:35 UTC, Nibuja05 commented on game/scripts/vscripts/core/weapon_base.ts
> +		if (this.wGetElement() === element) return true;
yes it needs to be. Too many adjustments for now, made a new Issue: #91

2021-05-16 10:37 UTC, Nibuja05 commented on game/scripts/vscripts/core/weapon_manager.ts
> +				maxLevel: 10,
done

2021-05-16 14:28 UTC, Shushishtok approved these changes

2021-05-16 14:28 UTC, merged